############## APPLICATION CONFIG ##############
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true # Habilita a compressão das respostas HTTP.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Lista separada por vírgulas de tipos MIME que devem ser compactados.
    min-response-size: 1024 # Define o tamanho mínimo da resposta (em bytes) para que a compressão seja aplicada.
  undertow:
    threads:
      worker: 64 # Geralmente isso deve ser razoavelmente alto, pelo menos 10 por núcleo da CPU: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # Um thread IO por núcleo da CPU é um padrão razoável: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
  application:
    name: admin-catalago-videos
  flyway:
    locations: classpath:db/migration
    enabled: true
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # É uma configuração em milliseconds. O ideal é manter baixo para que estoure timeout logo e não prenda as threads.
      max-lifetime: 600000 # Tempo máximo que uma conexão pode ficar aberta (10 min) - security.
      maximum-pool-size: 20 # Mantemos até no máx 20 conexões com o banco de dados. O ideal é manter baixo mesmo, pois é algo custoso para o banco gerenciar. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      "[hibernate.check_nullability]": true
      # Para aumentar a performance ao máximo, desabilitamos o auto-commit e o open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/

aws:
  s3:
    region: us-east-1


storage:
  catalogo-videos:
    bucket-name: admin-cat-videos
    filename-pattern: type-{type}
    location-pattern: videoId-{videoId}